var DomElements = {
    switchAutoButton: document.getElementById("switchAutoButton"),
    switch2DButton: document.getElementById("switch2DButton"),
    switch3DButton: document.getElementById("switch3DButton"),
    zoomInButton: document.getElementById("zoomInButton"),
    zoomOutButton: document.getElementById("zoomOutButton"),
    fullScreenButton: document.getElementById("fullScreenButton"),
    switchVRButton: document.getElementById("switchVRButton"),
    vrStartTip: document.getElementById("vrStartTip"),
    welcome: document.getElementById("welcome"),
    loading: document.getElementById("loading"),
    loadingTip: document.getElementById("loading_tip"),
    loadingProgressBar: document.getElementById("loading_progress_bar"),
    loading_bar: document.getElementById("loading_bar"),
    vrHouseContainer: document.getElementById("vr_house_container"),
    controlDiv: document.getElementById("controlDiv"),
    controlTip: document.getElementById("controlTip"),
    rotationTip: document.getElementById("rotationTip"),
    enterHotSpotTip: document.getElementById("enterHotSpotTip"),
    controllerLeft: document.getElementById("controller-left"),
    naviLeft: document.getElementById("naviLeft"),
    naviRight: document.getElementById("naviRight"),
    thumbnails: document.getElementById("thumbnails"),
    thumbnailList: document.getElementById("thumbnail-list"),
    thumbnailController: document.getElementById("thumbnail-controller"),
    thumbnailControlButton: document.getElementById("thumbnail-control-button"),
    enterPanoramaViewBtn: document.getElementById("enterPanoramaViewBtn"),
    largeViewSwitchController: document.getElementById("largeViewSwitchController"),
    largeViewSwitch2DButton: document.getElementById("largeViewSwitch2DButton"),
    largeViewSwitch3DButton: document.getElementById("largeViewSwitch3DButton")
}
module.exports = DomElements;
